/*
 * This file is generated by jOOQ.
 */
package com.skillup.infrastructure.jooq;


import com.skillup.infrastructure.jooq.tables.Commodity;
import com.skillup.infrastructure.jooq.tables.Order;
import com.skillup.infrastructure.jooq.tables.Promotion;
import com.skillup.infrastructure.jooq.tables.User;


/**
 * Convenience access to all tables in skillup.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>skillup.commodity</code>.
     */
    public static final Commodity COMMODITY = Commodity.COMMODITY;

    /**
     * The table <code>skillup.order</code>.
     */
    public static final Order ORDER = Order.ORDER;

    /**
     * The table <code>skillup.promotion</code>.
     */
    public static final Promotion PROMOTION = Promotion.PROMOTION;

    /**
     * The table <code>skillup.user</code>.
     */
    public static final User USER = User.USER;
}
